runtime: python311 # or another supported version

instance_class: F1
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /quote
  script: auto
  secure: always
  redirect_http_response_code: 301

- url: /shortquote
  script: auto
  secure: always
  redirect_http_response_code: 301

- url: /longquote
  script: auto
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301